services:
  # backend:
  #   container_name: backend-hoteles
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8001:8000"
  #   # depends_on:
  #   #   - postgres
  #   env_file:
  #     - ./.env
  #   environment:
  #     - SERVER_NAME=${DOMAIN?Variable not set}
  #     - SERVER_HOST=https://${DOMAIN?Variable not set}
  #   volumes:
  #     - ./backend/alembic:/app/alembic
  #     - ./backend/app/:/app/app

  frontend:
    container_name: frontend-hoteles
    build:
      context: ./frontend
      target: dev
    env_file:
    - ./.env
    restart: always
    command: npx next dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /frontend/node_modules
      - /frontend/.next
    ports:
      - 3001:3000

  # postgres:
  #   container_name: postgres-hoteles
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: 
  #     POSTGRES_PASSWORD: 
  #     POSTGRES_DB: 
  #   ports:
  #     - "5433:5432"
